### ISSUE TITLE
When can we see the project source code?

### ISSUE THREAD

**Issue by fishmingyu** [AutomataLab/Subway#1]
Dear author of Subway,
Hi, I am reading your article these days and want to see the source code to deepen understanding. In your readme, you promised the source code will be posted around mid-May, but May is coming to an end. I would appreciate it if you can reply me in this issue. Thanks!

**Comment by zhijia** [comment]
Hi fishmingyu,

We are releasing the code. You should be able to see it by tomorrow (May 27th). Thanks for your interests.

**Comment by fishmingyu** [comment]
Thank you very much!
