### ISSUE TITLE
Where is the PageRank

### ISSUE THREAD

**Issue by trq2014** [AutomataLab/Subway#2]
Where is the PageRank

**Comment by AutomataLab** [comment]
PR was not released together with the other benchmarks, but we plan to release it. Please stay tuned. Thanks.

**Comment by AiX-im** [comment]
After make, run the instruction. / bfs-sync -- input. / edge_ 875713.el

The tips are as follows:
Reading the input graph from the following file:
>> ./edge_875713.el
Done reading.
Number of nodes = 875713
Number of edges = 9238952
Graph Reading finished in 1.80066 (s).
GPUassert: out of memory subgraph.cu 40

Why is it out of memory

**Comment by amirnodehi** [comment]
PageRank is added to the repository.
