### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AiX-im** [AutomataLab/Subway#3]
After make, run the instruction. / bfs-sync -- input. / edge_ 875713.el

The tips are as follows:
Reading the input graph from the following file:

        ./edge_875713.el
        Done reading.
        Number of nodes = 875713
        Number of edges = 9238952
        Graph Reading finished in 1.80066 (s).
        GPUassert: out of memory subgraph.cu 40

Why is it out of memory

**Comment by amirnodehi** [comment]
Please send me the graph file.

**Comment by AiX-im** [comment]
Sorry, I didn't reply you in time. The problem has been solved.
I modified the code in subgraph.cu line 24 from
max_partition_size = 0.9 * (dev.totalGlobalMem - 8*4*num_nodes) / sizeof(E);  to
max_partition_size = 0.1 * (dev.totalGlobalMem - 8*4*2*num_nodes) / sizeof(E);
I consider whether the original code will inevitably cause problems, regardless of the size of the graph.
But I don't know whether such modification will affect the performance of the system. Please advise me.
